name: Deploy Laravel Sail (Remote)
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue por SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key:  ${{ secrets.KEY }}
          script: |
            set -e
            cd /var/www/html/WebAutoGit
            git config --global --add safe.directory /var/www/html/WebAutoGit
            git pull